### ISSUE TITLE
ROM/Course Expansion

### ISSUE THREAD

**Issue by xnamkcor** [devinacker/kdceditor#1]
Would it be possible to add an option in the program to allocate more space for larger course(larger tilemaps)? And additionally, if possible, expand the total size of the ROM?

**Comment by devinacker** [comment]
ROM expansion already happens automatically on saving (all new course data is written to expanded ROM space, leaving all of the original data intact). 

The tile map etc. size limitations are due to limits on the amount of RAM that the game allocates to those things during gameplay; expanding that wouldn't be possible without massively rewriting other game code to account for it, which isn't really feasible.

**Comment by xnamkcor** [comment]
The best I can think of to improve that situation is try to reduce the memory use of the tiles, but that would take more coding that just a simple editor.

**Comment by devinacker** [comment]
That would definitely take even more work in modifying the game's internals than simply giving the tile maps more RAM to work with. Currently the entire uncompressed tilemap is loaded into RAM all at once, which is the reason for the hard limit on space; it theoretically would be possible to totally redesign parts of the level format (and rewrite lots of the game code that deals with it) so that smaller parts of the map are loaded from the ROM on the fly during gameplay (but again, not really feasible).
