### ISSUE TITLE
Limitation Removal

### ISSUE THREAD

**Issue by xnamkcor** [devinacker/kdceditor#3]
Could you remove the 31 height limitation(98 is the highest I tested with no graphical or physical problems).

Also, does the game's engine require that there be geography for there to be a gimmick on that geography? For example, would a floating booster be possible?

**Comment by devinacker** [comment]
31 was a pretty arbitrary limit I chose early on; the reason is that level height often has a much bigger effect on tilemap size than length or width do, and that size is unfortunately limited (because of reasons I mentioned in issue #1). Because of those limits, having an extremely high-altitude course may seem to work at first, but it makes it hard to have reasonable width/length values before tile map memory issues start to occur.

As for the second question, I don't actually remember if putting obstacles on top of empty space works correctly or not. I'll have to experiment again with that later.

**Comment by devinacker** [comment]
I may end up revisiting the level height restriction just a bit, given how arbitrary it was in the first place and the fact that people seem to have been wanting to see it raised. I'll have to experiment with it the next time I'm working on this.

**Comment by xnamkcor** [comment]
If a tall wall of tiles is placed closes to the person, do tiles behind it not count towards the tile limit?

**Comment by devinacker** [comment]
Only the tiles that are actually visible on screen (on either layer 1 or layer 2) count towards the limit, so the effect of placing a tall wall partially depends on what it's covering up behind it.

Anyway, the new release has the height, length and width levels raised, so I'm going to close this.
